version: '2'

services:
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./wordpress:/var/lib/mysql
    environment:  
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=895fa1sr
      
  wordpress: 
    depends_on:
     - mysql
    image: wordpress
    volumes:
     - ./wordpress:/var/www/html
    ports:
      - 50:23
    environment:
      - WORDPRESS_DB_PASSWORD=895fa1sr
      
